pipeline:
  luacheck:
    image: codeclimate/codeclimate-luacheck
    commands:
      - luacheck .

  notify:
    image: plugins/slack
    username: drone
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]

  deploy:
    image: plugins/webhook
    secrets: [ webhook_username, webhook_password, webhook_urls ]
    when:
      status: [ success ]
